# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'product_master.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QTextEdit,
    QWidget)

class Ui_product_label(object):
    def setupUi(self, product_label):
        if not product_label.objectName():
            product_label.setObjectName(u"product_label")
        product_label.resize(1050, 626)
        self.product_label_2 = QLabel(product_label)
        self.product_label_2.setObjectName(u"product_label_2")
        self.product_label_2.setGeometry(QRect(280, 10, 531, 71))
        font = QFont()
        font.setFamilies([u"Comic Sans MS"])
        font.setPointSize(32)
        font.setUnderline(True)
        self.product_label_2.setFont(font)
        self.product_label_3 = QLabel(product_label)
        self.product_label_3.setObjectName(u"product_label_3")
        self.product_label_3.setGeometry(QRect(20, 130, 211, 41))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(22)
        self.product_label_3.setFont(font1)
        self.img_pre = QLabel(product_label)
        self.img_pre.setObjectName(u"img_pre")
        self.img_pre.setGeometry(QRect(800, 120, 231, 241))
        self.upl_img = QPushButton(product_label)
        self.upl_img.setObjectName(u"upl_img")
        self.upl_img.setGeometry(QRect(850, 60, 121, 41))
        font2 = QFont()
        font2.setFamilies([u"Consolas"])
        font2.setPointSize(18)
        font2.setUnderline(True)
        self.upl_img.setFont(font2)
        self.upl_img.setStyleSheet(u"QPushButton:hover{\\n\"\n"
"\"background-color: blue;\\n\"\n"
"}\n"
"")
        self.product_input = QLineEdit(product_label)
        self.product_input.setObjectName(u"product_input")
        self.product_input.setGeometry(QRect(230, 140, 221, 31))
        font3 = QFont()
        font3.setPointSize(18)
        self.product_input.setFont(font3)
        self.cat_label = QLabel(product_label)
        self.cat_label.setObjectName(u"cat_label")
        self.cat_label.setGeometry(QRect(60, 190, 151, 51))
        self.cat_label.setFont(font1)
        self.cat_input = QLineEdit(product_label)
        self.cat_input.setObjectName(u"cat_input")
        self.cat_input.setGeometry(QRect(240, 200, 191, 31))
        self.cat_input.setFont(font3)
        self.subcat_label = QLabel(product_label)
        self.subcat_label.setObjectName(u"subcat_label")
        self.subcat_label.setGeometry(QRect(50, 250, 151, 51))
        self.subcat_label.setFont(font3)
        self.subcat_input = QLineEdit(product_label)
        self.subcat_input.setObjectName(u"subcat_input")
        self.subcat_input.setGeometry(QRect(240, 260, 171, 31))
        self.subcat_input.setFont(font3)
        self.sku_label = QLabel(product_label)
        self.sku_label.setObjectName(u"sku_label")
        self.sku_label.setGeometry(QRect(570, 110, 111, 41))
        self.sku_label.setFont(font1)
        self.sku_input = QLineEdit(product_label)
        self.sku_input.setObjectName(u"sku_input")
        self.sku_input.setGeometry(QRect(530, 160, 231, 41))
        font4 = QFont()
        font4.setFamilies([u"Consolas"])
        font4.setPointSize(18)
        self.sku_input.setFont(font4)
        self.bar_label = QLabel(product_label)
        self.bar_label.setObjectName(u"bar_label")
        self.bar_label.setGeometry(QRect(50, 330, 121, 51))
        self.bar_label.setFont(font1)
        self.bar_input = QLineEdit(product_label)
        self.bar_input.setObjectName(u"bar_input")
        self.bar_input.setGeometry(QRect(190, 341, 241, 31))
        self.bar_input.setFont(font4)
        self.desc_label = QLabel(product_label)
        self.desc_label.setObjectName(u"desc_label")
        self.desc_label.setGeometry(QRect(20, 400, 221, 61))
        font5 = QFont()
        font5.setFamilies([u"Consolas"])
        font5.setPointSize(24)
        self.desc_label.setFont(font5)
        self.desc_input = QTextEdit(product_label)
        self.desc_input.setObjectName(u"desc_input")
        self.desc_input.setGeometry(QRect(100, 470, 351, 131))
        self.desc_input.setFont(font4)
        self.unit_input = QComboBox(product_label)
        self.unit_input.addItem("")
        self.unit_input.addItem("")
        self.unit_input.addItem("")
        self.unit_input.setObjectName(u"unit_input")
        self.unit_input.setGeometry(QRect(620, 230, 61, 41))
        self.unit_input.setEditable(True)
        self.unit_label = QLabel(product_label)
        self.unit_label.setObjectName(u"unit_label")
        self.unit_label.setGeometry(QRect(540, 230, 71, 41))
        font6 = QFont()
        font6.setPointSize(24)
        self.unit_label.setFont(font6)
        self.tax_label = QLabel(product_label)
        self.tax_label.setObjectName(u"tax_label")
        self.tax_label.setGeometry(QRect(800, 390, 101, 61))
        self.tax_label.setFont(font5)
        self.tax_input = QDoubleSpinBox(product_label)
        self.tax_input.setObjectName(u"tax_input")
        self.tax_input.setGeometry(QRect(930, 400, 71, 41))
        font7 = QFont()
        font7.setFamilies([u"Comic Sans MS"])
        font7.setPointSize(12)
        self.tax_input.setFont(font7)
        self.label = QLabel(product_label)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(810, 460, 91, 61))
        self.label.setFont(font1)
        self.submit_btn = QPushButton(product_label)
        self.submit_btn.setObjectName(u"submit_btn")
        self.submit_btn.setGeometry(QRect(930, 560, 111, 41))
        font8 = QFont()
        font8.setFamilies([u"Consolas"])
        font8.setPointSize(16)
        self.submit_btn.setFont(font8)
        self.clear_btn = QPushButton(product_label)
        self.clear_btn.setObjectName(u"clear_btn")
        self.clear_btn.setGeometry(QRect(810, 560, 101, 41))
        self.clear_btn.setFont(font8)
        self.doubleSpinBox = QDoubleSpinBox(product_label)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(930, 470, 71, 41))
        self.doubleSpinBox.setFont(font7)
        self.doubleSpinBox.setMaximum(9999999.990000000223517)

        self.retranslateUi(product_label)

        QMetaObject.connectSlotsByName(product_label)
    # setupUi

    def retranslateUi(self, product_label):
        product_label.setWindowTitle(QCoreApplication.translate("product_label", u"Product Master Creation", None))
        self.product_label_2.setText(QCoreApplication.translate("product_label", u"Product Master Creation", None))
        self.product_label_3.setText(QCoreApplication.translate("product_label", u"Product Name", None))
        self.img_pre.setText("")
        self.upl_img.setText(QCoreApplication.translate("product_label", u"Upload", None))
        self.cat_label.setText(QCoreApplication.translate("product_label", u"Category", None))
        self.subcat_label.setText(QCoreApplication.translate("product_label", u"Sub Catogory", None))
        self.sku_label.setText(QCoreApplication.translate("product_label", u"SKU ID", None))
        self.bar_label.setText(QCoreApplication.translate("product_label", u"Barcode", None))
        self.desc_label.setText(QCoreApplication.translate("product_label", u"Description", None))
        self.unit_input.setItemText(0, QCoreApplication.translate("product_label", u"Kg", None))
        self.unit_input.setItemText(1, QCoreApplication.translate("product_label", u"meter", None))
        self.unit_input.setItemText(2, QCoreApplication.translate("product_label", u"L", None))

        self.unit_label.setText(QCoreApplication.translate("product_label", u"Unit", None))
        self.tax_label.setText(QCoreApplication.translate("product_label", u"Tax %", None))
        self.label.setText(QCoreApplication.translate("product_label", u"Price", None))
        self.submit_btn.setText(QCoreApplication.translate("product_label", u"Save", None))
        self.clear_btn.setText(QCoreApplication.translate("product_label", u"Clear", None))
    # retranslateUi

