# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sales_form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QFrame,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpinBox, QWidget)

class Ui_unit_input_2(object):
    def setupUi(self, unit_input_2):
        if not unit_input_2.objectName():
            unit_input_2.setObjectName(u"unit_input_2")
        unit_input_2.resize(829, 550)
        self.salesform_label = QLabel(unit_input_2)
        self.salesform_label.setObjectName(u"salesform_label")
        self.salesform_label.setGeometry(QRect(270, 10, 241, 81))
        font = QFont()
        font.setFamilies([u"Comic Sans MS"])
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        self.salesform_label.setFont(font)
        self.cust_label = QLabel(unit_input_2)
        self.cust_label.setObjectName(u"cust_label")
        self.cust_label.setGeometry(QRect(20, 110, 231, 51))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(24)
        self.cust_label.setFont(font1)
        self.product_label = QLabel(unit_input_2)
        self.product_label.setObjectName(u"product_label")
        self.product_label.setGeometry(QRect(30, 220, 241, 51))
        self.product_label.setFont(font1)
        self.qty_label = QLabel(unit_input_2)
        self.qty_label.setObjectName(u"qty_label")
        self.qty_label.setGeometry(QRect(40, 300, 151, 51))
        self.qty_label.setFont(font1)
        self.line = QFrame(unit_input_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 160, 831, 20))
        self.line.setFrameShadow(QFrame.Shadow.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.rate_label = QLabel(unit_input_2)
        self.rate_label.setObjectName(u"rate_label")
        self.rate_label.setGeometry(QRect(520, 210, 171, 51))
        self.rate_label.setFont(font1)
        self.unit_label = QLabel(unit_input_2)
        self.unit_label.setObjectName(u"unit_label")
        self.unit_label.setGeometry(QRect(70, 400, 91, 41))
        self.unit_label.setFont(font1)
        self.tax_label = QLabel(unit_input_2)
        self.tax_label.setObjectName(u"tax_label")
        self.tax_label.setGeometry(QRect(600, 290, 101, 51))
        self.tax_label.setFont(font1)
        self.total_label = QLabel(unit_input_2)
        self.total_label.setObjectName(u"total_label")
        self.total_label.setGeometry(QRect(460, 430, 191, 41))
        self.total_label.setFont(font1)
        self.line_2 = QFrame(unit_input_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(657, 400, 171, 20))
        self.line_2.setFrameShadow(QFrame.Shadow.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setMidLineWidth(2)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.unit_input = QComboBox(unit_input_2)
        self.unit_input.addItem("")
        self.unit_input.addItem("")
        self.unit_input.addItem("")
        self.unit_input.setObjectName(u"unit_input")
        self.unit_input.setGeometry(QRect(180, 400, 61, 41))
        self.unit_input.setEditable(True)
        self.customer_input = QLineEdit(unit_input_2)
        self.customer_input.setObjectName(u"customer_input")
        self.customer_input.setGeometry(QRect(270, 121, 261, 31))
        font2 = QFont()
        font2.setFamilies([u"Consolas"])
        font2.setPointSize(18)
        self.customer_input.setFont(font2)
        self.product_input = QLineEdit(unit_input_2)
        self.product_input.setObjectName(u"product_input")
        self.product_input.setGeometry(QRect(270, 231, 211, 31))
        self.product_input.setFont(font2)
        self.qty_input = QSpinBox(unit_input_2)
        self.qty_input.setObjectName(u"qty_input")
        self.qty_input.setGeometry(QRect(210, 310, 61, 41))
        font3 = QFont()
        font3.setFamilies([u"Consolas"])
        font3.setPointSize(16)
        self.qty_input.setFont(font3)
        self.rate_input = QDoubleSpinBox(unit_input_2)
        self.rate_input.setObjectName(u"rate_input")
        self.rate_input.setGeometry(QRect(710, 220, 81, 41))
        font4 = QFont()
        font4.setFamilies([u"Consolas"])
        font4.setPointSize(12)
        self.rate_input.setFont(font4)
        self.tax_input = QDoubleSpinBox(unit_input_2)
        self.tax_input.setObjectName(u"tax_input")
        self.tax_input.setGeometry(QRect(720, 300, 71, 41))
        font5 = QFont()
        font5.setFamilies([u"Comic Sans MS"])
        font5.setPointSize(12)
        self.tax_input.setFont(font5)
        self.totale_rate_label = QLabel(unit_input_2)
        self.totale_rate_label.setObjectName(u"totale_rate_label")
        self.totale_rate_label.setGeometry(QRect(680, 430, 121, 31))
        font6 = QFont()
        font6.setFamilies([u"Comic Sans MS"])
        font6.setPointSize(16)
        self.totale_rate_label.setFont(font6)
        self.submit_btn = QPushButton(unit_input_2)
        self.submit_btn.setObjectName(u"submit_btn")
        self.submit_btn.setGeometry(QRect(310, 500, 141, 41))
        font7 = QFont()
        font7.setFamilies([u"Comic Sans MS"])
        font7.setPointSize(21)
        font7.setBold(True)
        self.submit_btn.setFont(font7)
        self.calc_btn = QPushButton(unit_input_2)
        self.calc_btn.setObjectName(u"calc_btn")
        self.calc_btn.setGeometry(QRect(700, 360, 101, 31))
        font8 = QFont()
        font8.setFamilies([u"Comic Sans MS"])
        font8.setPointSize(12)
        font8.setBold(False)
        self.calc_btn.setFont(font8)
        self.clear_btn = QPushButton(unit_input_2)
        self.clear_btn.setObjectName(u"clear_btn")
        self.clear_btn.setGeometry(QRect(10, 500, 81, 41))
        font9 = QFont()
        font9.setPointSize(18)
        font9.setUnderline(False)
        self.clear_btn.setFont(font9)

        self.retranslateUi(unit_input_2)

        QMetaObject.connectSlotsByName(unit_input_2)
    # setupUi

    def retranslateUi(self, unit_input_2):
        unit_input_2.setWindowTitle(QCoreApplication.translate("unit_input_2", u"Sales Form", None))
        self.salesform_label.setText(QCoreApplication.translate("unit_input_2", u"Sales Form", None))
        self.cust_label.setText(QCoreApplication.translate("unit_input_2", u"Customer Name", None))
        self.product_label.setText(QCoreApplication.translate("unit_input_2", u"Product Name", None))
        self.qty_label.setText(QCoreApplication.translate("unit_input_2", u"Quantity", None))
        self.rate_label.setText(QCoreApplication.translate("unit_input_2", u"Rate/Unit", None))
        self.unit_label.setText(QCoreApplication.translate("unit_input_2", u"Unit", None))
        self.tax_label.setText(QCoreApplication.translate("unit_input_2", u"Tax %", None))
        self.total_label.setText(QCoreApplication.translate("unit_input_2", u"Total Rate", None))
        self.unit_input.setItemText(0, QCoreApplication.translate("unit_input_2", u"Kg", None))
        self.unit_input.setItemText(1, QCoreApplication.translate("unit_input_2", u"meter", None))
        self.unit_input.setItemText(2, QCoreApplication.translate("Form", u"pcs", None))

        self.totale_rate_label.setText("")
        self.submit_btn.setText(QCoreApplication.translate("unit_input_2", u"Submit", None))
        self.calc_btn.setText(QCoreApplication.translate("unit_input_2", u"Calculate", None))
        self.clear_btn.setText(QCoreApplication.translate("unit_input_2", u"Clear", None))
    # retranslateUi

